name: CI/CD with terraform
on:
  push:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCES_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: eu-west-3

jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_wrapper: false

        - name: Terraform init
          id: init
          run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=eu-west-3"
          working-directory: ./terraform

        - name: Terraform Plan
          id: plan
          run: |-
            terraform plan \
              -var="region=eu-west-3" \
              -var="public_key=$PUBLIC_SSH_KEY" \
              -var="private_key=$PRIVATE_SSH_KEY" \
              -var="key_name=deployer-key" \
              -out=PLAN
          working-directory: ./terraform

        - name: Terraform Apply
          id: apply
          run: terraform apply APPLY
          working-directory: ./terraform